Update termux-camera-photo
termux/termux-api-package pull request #142
Opened 2021-10-31 07:59 UTC by SDRausty

2021-10-31 17:53 UTC, SDRausty commented
https://github.com/termux/termux-api-package/issues/146

2022-03-14 09:05 UTC, Grimler91 requested changes
Please update the commit message to something more descriptive. 

The PR also doesn't apply, so please rebase.

2022-03-14 09:05 UTC, Grimler91 commented on scripts/termux-camera-photo
> -    echo "Usage: termux-camera-photo [-c camera-id] output-file"
Changing from termux-camera-photo to SCRIPTNAME here is good

2022-03-14 09:05 UTC, Grimler91 commented on scripts/termux-camera-photo
> -    echo "  -c camera-id  ID of the camera to use (see termux-camera-info), default: 0"
Changing from termux-camera-photo to SCRIPTNAME here is good

2022-03-17 06:35 UTC, SDRausty commented
> The PR also doesn't apply, so please rebase.

I have no idea how to do this as the original fork is deleted.

2022-03-21 21:43 UTC, closed without merging